[package]
name = "actixweb-sqlx-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.4", features = [ "runtime-actix-native-tls" , "postgres" ] }
actix-web = "3"